# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 06:41
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_id', models.IntegerField(db_index=True)),
                ('arrival', models.TimeField(blank=True, null=True)),
                ('departure', models.TimeField(blank=True, null=True)),
                ('halt', models.IntegerField(blank=True, null=True)),
                ('stop_number', models.IntegerField()),
                ('minor_stop_number', models.IntegerField()),
                ('day', models.IntegerField()),
                ('distance_travelled', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_id', models.IntegerField(db_index=True)),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=512)),
                ('number', models.IntegerField(db_index=True)),
                ('return_train', models.IntegerField(db_index=True)),
                ('duration_h', models.IntegerField()),
                ('duration_m', models.IntegerField()),
                ('zone', models.CharField(blank=True, max_length=16)),
                ('date_from', models.CharField(blank=True, max_length=32)),
                ('date_to', models.CharField(blank=True, max_length=32)),
                ('number_of_halts', models.IntegerField(null=True)),
                ('typ', models.CharField(blank=True, max_length=16)),
                ('departure', models.TimeField(blank=True, null=True)),
                ('arrival', models.TimeField(blank=True, null=True)),
                ('distance', models.IntegerField()),
                ('departure_days', models.CharField(blank=True, max_length=16)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('classes', models.CharField(blank=True, max_length=32)),
                ('chair_car', models.BooleanField()),
                ('sleeper', models.BooleanField()),
                ('first_class', models.BooleanField()),
                ('third_ac', models.BooleanField()),
                ('second_ac', models.BooleanField()),
                ('first_ac', models.BooleanField()),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_from', to='india.Station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_to', to='india.Station')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='india.Station'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='india.Train'),
        ),
    ]
