# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('india', '0002_auto_20160319_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='number',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='train',
            name='return_train',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
