# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('india', '0003_auto_20160319_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='data_id',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
