# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('india', '0004_auto_20160319_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
