# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('india', '0005_auto_20160319_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='india.Station'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='india.Train'),
        ),
    ]
