# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('india', '0007_auto_20160320_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
